services:
   #  1. Database
   mongo:
      image: mongo
      volumes:
         - ./mongo-data:/data/db

   #  2. Message Queue
   rabbitmq:
      image: rabbitmq:3-management
      ports:
         - "15672:15672" # Dashboard admin RabbitMQ

   #  3. Web App
   web_app:
      build: . # Build dari folder saat ini
      command: npm run dev # development
      ports:
         - "80:3000" # Map port 80 VPS ke port 3000 container
      depends_on:
         - mongo
         - rabbitmq
      volumes:
         - .:/app
         - /app/node_modules
         - temp_uploads:/app/temp # Shared volume buat simpan foto sementara

   #  4. Background Worker
   worker_service:
      build: . # Build dari folder yang sama (karena satu repo)
      command: npm run worker:dev # dev
      depends_on:
         - rabbitmq
         - web_app
      environment:
         - MONGO_URI=mongodb://mongo:27017/db_inventaris
         - RABBITMQ_URI=amqp://rabbitmq
         - MINIO_ENDPOINT=minio
         - MINIO_PORT=9000
         - MINIO_ACCESS_KEY=admin
         - MINIO_SECRET_KEY=password123
      volumes:
         - .:/app
         - /app/node_modules
         - temp_uploads:/app/temp

   minio:
      image: minio/minio
      ports:
         - "9000:9000" # Port API (Untuk koneksi backend)
         - "9001:9001" # Port Console (Untuk buka UI MinIO di browser)
      environment:
         MINIO_ROOT_USER: admin
         MINIO_ROOT_PASSWORD: password123
      command: server /data --console-address ":9001"
      volumes:
         - minio_data:/data

volumes:
   temp_uploads:
   minio_data:
